[project]
name = "dof-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pymupdf==1.26.5",
    "openai",
    "langchain[openai]",
    "langchain-core",
    "langchain-openai",
    "langchain-milvus",
    "langchain-postgres",
    "langgraph",
    "langgraph-checkpoint-sqlite",
    "langgraph-checkpoint-postgres",
    "langmem",
    "pymilvus",
    "psycopg[binary]",
    "psycopg2",
    "tiktoken",
    "fastapi",
    "uvicorn[standard]",
    "gunicorn",
    "unstructured[pdf]",
    "dropbox",
    "dotenv",
    "pillow",
    "pwdlib[argon2]",
    "pyjwt",
    "uuid",
    "pydantic",
    "markdown-it-py",
    "mdit-py-plugins",
    "argcomplete",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "matplotlib==3.7.5",
    "ipympl==0.9.3",
    "notebook",
]
