[project]
name = "dof-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pymupdf",
    "tiktoken",
    "langchain",
    "openai",
    "fastapi",
    "uvicorn",
    "dropbox",
    "pymilvus",
    "dotenv",
    "pillow",
]

[project.optional-dependencies]
dev = [
    "matplotlib==3.7.5",
    "ipympl==0.9.3",
    "notebook",
]
