[project]
name = "dof-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "numpy",
    "pymupdf==1.26.5",
    "openai",
    "langchain[openai]",
    "langchain-core",
    "langchain-openai",
    "langchain-milvus",
    "langchain-postgres",
    "langgraph",
    "langgraph-checkpoint-sqlite",
    "langgraph-checkpoint-postgres",
    "langmem",
    "pymilvus",
    "psycopg[binary]",
    "psycopg2-binary",
    "tiktoken",
    "fastapi",
    "uvicorn[standard]",
    "gunicorn",
    "unstructured[pdf]>=0.12",
    "onnxruntime>=1.17",
    "onnx>=1.15",
    "ml-dtypes>=0.3.1",
    "opencv-python-headless",
    "dropbox",
    "dotenv",
    "pillow",
    "pwdlib[argon2]",
    "pyjwt",
    "uuid",
    "pydantic",
    "markdown-it-py",
    "mdit-py-plugins",
    "argcomplete",
    "unidecode",
    "pypdf",
    "jsonb",
    "tqdm",
    "gptcache",
    "watchdog",
    "termcolor",
]

[project.optional-dependencies]
dev = [
    "ipykernel",
    "matplotlib==3.7.5",
    "ipympl==0.9.3",
    "notebook",
]
