from pydantic import BaseModel, Field, NonNegativeInt
from typing import List, Dict, Any, Self, Tuple, Annotated
from langgraph.graph import MessagesState
from langmem.short_term import RunningSummary


class GradeDocument(BaseModel):
    """Document with its relevance score."""

    document_name: str = Field(
        description="The name or identifier of the document"
    )
    page_indices: List[int] = Field(
        description="The page indices of the document, found in metadata (page_indices)"
    )
    page_labels: List[str] = Field(
        description="The page labels of the document, found in metadata (page_labels)"
    )
    score: float = Field(
        description="Relevance score between 0 and 1"
    )


class GradeResults(BaseModel):
    """List of documents with their relevance scores."""

    documents: List[GradeDocument] = Field(
        description="List of documents with relevance scores"
    )


    def __getitem__(self, index: int) -> GradeDocument:
        return self.documents[index]
    

    def __iter__(self):
        for doc in self.documents:
            yield doc
    

    def __len__(self) -> int:
        return len(self.documents)
    

    def filter_by_score(self, threshold: float) -> Self:
        filtered_docs = [doc for doc in self.documents if doc.score >= threshold]
        return GradeResults(documents=filtered_docs)
    

    def merge_same_documents(self) -> Self:
        for i in range(len(self.documents)):
            for j in range(len(self.documents) - 1, i, -1):
                if self.documents[i].document_name == self.documents[j].document_name:
                    # Merge page labels and pages
                    self.documents[i].page_labels = list(set(self.documents[i].page_labels + self.documents[j].page_labels))
                    self.documents[i].page_indices = list(set(self.documents[i].page_indices + self.documents[j].page_indices))
                    # Remove the duplicate document
                    del self.documents[j]

        return self
    

class Citation(BaseModel):
    documentName: str = Field(
        description='The full name of the pdf document'
    )
    pageLabels: List[str] = Field(
        description=(
            'List of the pdf page labels (the printed page numbers, as opposed to the internal PDF page indices). '
            'Each label must correspond positionally to the matching entry in pageIndices.'
        )
    )
    pageIndices: List[NonNegativeInt] = Field(
        description=(
            'List of 0-based page indices (internal PDF position, NOT the printed page number). '
            'Index 0 = first page of the PDF, index 1 = second page, etc. '
            'Each index must correspond positionally to the matching entry in pageLabels.'
        )
    )


class ResponseOutput(BaseModel):
    response: str = Field(
        description="The answer generated by the model"
    )
    summaryTitle: str = Field(
        description="A brief title summarizing the answer"
    )
    citations: List[Citation] = Field(
        description="List of citations used in the answer"
    )

    def __contains__(self, document_name: str) -> bool:
        for citation in self.citations:
            if citation.documentName == document_name:
                return True
        return False
    
    def __getitem__(self, document_name: str) -> Citation:
        for citation in self.citations:
            if citation.documentName == document_name:
                return citation
        
        raise KeyError(f"Document name '{document_name}' not found in citations.")
    
    def update_citation_pages(self, new_pdf_pages: list[int], new_page_labels: list[str], document_name: str) -> None:
        if document_name not in self:
            return
        
        citation = self[document_name]
        if citation is None:
            return
        
        try:
            indices = citation.pageIndices
            citation.pageIndices = [new_pdf_pages[index] + 1 for index in indices]
            citation.pageLabels = [new_page_labels[index] for index in indices]
        except:
            print('Not able to write citation!')


class DocumentPDF(BaseModel):
    name: str
    pages: List[int]
    pageLabels: List[int]
    data: str


class State(MessagesState):
    context: dict[str, RunningSummary]
    documents: List[DocumentPDF]
    parsed: ResponseOutput
    cache: dict[str, Any]