from pydantic import BaseModel, Field, NonNegativeInt
from typing import List, Dict, Any, Self, Tuple, Annotated, Optional
from langgraph.graph import MessagesState
from langmem.short_term import RunningSummary


class GradeDocument(BaseModel):
    """Document with its relevance score."""

    document_name: str = Field(
        description="The full name of the pdf document, including extension (e.g. 'example.pdf')"
    )
    page_indices: List[int] = Field(
        description="The page indices of the document, found in metadata (page_indices)"
    )
    page_labels: List[str] = Field(
        description="The page labels of the document, found in metadata (page_labels)"
    )
    score: float = Field(
        description="Relevance score between 0 and 1"
    )


class GradeResults(BaseModel):
    """List of documents with their relevance scores."""

    documents: List[GradeDocument] = Field(
        description="List of documents with relevance scores"
    )


    def __getitem__(self, index: int) -> GradeDocument:
        return self.documents[index]
    

    def __iter__(self):
        for doc in self.documents:
            yield doc
    

    def __len__(self) -> int:
        return len(self.documents)
    

    def filter_by_score(self, threshold: float) -> Self:
        filtered_docs = [doc for doc in self.documents if doc.score >= threshold]
        return GradeResults(documents=filtered_docs)
    

    def merge_same_documents(self) -> Self:
        for i in range(len(self.documents)):
            for j in range(len(self.documents) - 1, i, -1):
                if self.documents[i].document_name == self.documents[j].document_name:
                    # Merge page labels and pages
                    self.documents[i].page_labels = list(set(self.documents[i].page_labels + self.documents[j].page_labels))
                    self.documents[i].page_indices = list(set(self.documents[i].page_indices + self.documents[j].page_indices))
                    # Remove the duplicate document
                    del self.documents[j]

        return self
    

class Citation(BaseModel):
    document_name: str = Field(
        description='The full name of the pdf document, including extension (e.g. "example.pdf")'
    )
    page_labels: List[str] = Field(
        description=(
            'List of the pdf page labels (the printed page numbers, as opposed to the internal PDF page indices). '
            'Each label must correspond positionally to the matching entry in page_indices.'
        )
    )
    page_indices: List[NonNegativeInt] = Field(
        description=(
            'List of 0-based page indices (internal PDF position, NOT the printed page number). '
            'Index 0 = first page of the PDF, index 1 = second page, etc. '
            'Each index must correspond positionally to the matching entry in page_labels.'
        )
    )


class ResponseOutput(BaseModel):
    response: str = Field(
        description="The answer generated by the model"
    )
    summary_title: str = Field(
        description="A brief title summarizing the answer"
    )
    citations: List[Citation] = Field(
        description="List of citations used in the answer"
    )
    cache_id: Optional[str | None] = Field(
        default=None,
        description="Do not set this field. Will be populated with the ID of the semantic cache entry if the response was retrieved from cache."
    )

    def __contains__(self, document_name: str) -> bool:
        for citation in self.citations:
            if citation.document_name == document_name:
                return True
        return False
    
    def __getitem__(self, document_name: str) -> Citation:
        for citation in self.citations:
            if citation.document_name == document_name:
                return citation
        
        raise KeyError(f"Document name '{document_name}' not found in citations.")


class DocumentPDF(BaseModel):
    name: str
    page_indices: List[int]
    page_labels: List[int]
    data: str


class State(MessagesState):
    context: dict[str, RunningSummary]
    documents: List[DocumentPDF]
    parsed: ResponseOutput
    cache: dict[str, Any]
    check_cache: bool