FROM python:3.12.10-slim

RUN apt-get update && apt-get install -y \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender1 \
    libgl1 \
    libxcb1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY /src /app/src
COPY /document_processing /app/document_processing

RUN apt-get update && apt-get install -y systemctl
CMD ["sh", "-c", "cd /app/src && python3 setup_database.py && gunicorn main:app"]