services:
  postgres:
    image: pgvector/pgvector:pg18
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_backend
    volumes:
      - pg-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build: .
    container_name: backend
    volumes:
      # Bind mounts for source code, DEV ONLY
      - type: bind
        source: ./src
        target: /app/src
      # Bind mounts for local document storage, example:
      # - type: bind
      #     source: /path/to/local/documents (relative or absolute path)
      #     target: ${MOUNT_PATH}/path/inside/container (MOUNT_PATH is defined as mount path inside container and is required)
      - type: bind
        source: ../pdfs
        target: ${MOUNT_PATH}/test_documents
      # Stored volume for configs, logs, partitions and default documents
      - data:/app/data
    ports:
      - "8015:8015"
    environment:
      - DATA_PATH=/app/data/
      - MOUNT_PATH=${MOUNT_PATH}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dof.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge

# Define volumes for persistent data storage
# Used for database, default documents, configs, logs and partitions
volumes:
  pg-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/pg-data
      o: bind
  pgadmin-data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/pgadmin-data
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_PATH}/data
      o: bind