services:
  postgres:
    image: pgvector/pgvector:pg18
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: app_backend
    volumes:
      - pg-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build: .
    container_name: backend
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/data:/data
    ports:
      - "8015:8015"
    environment:
      - DATA_PATH=../data/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - API_ALGORITHM=${API_ALGORITHM}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  default:
    name: milvus
  postgres:
    driver: bridge

volumes:
  pg-data:
  pgadmin-data: