[project]
name = "dof-internship"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.10"
dependencies = [
    "numpy",
    "pymupdf==1.26.5",
    "openai",
    "langchain-core",
    "langchain-openai",
    "langchain-postgres",
    "langgraph",
    "langgraph-checkpoint-postgres",
    "langmem",
    "pymilvus",
    "psycopg[binary]",
    "psycopg2-binary",
    "tiktoken",
    "fastapi",
    "uvicorn[standard]",
    "gunicorn",
    "python-multipart",
    "unstructured[pdf]>=0.12",
    # "onnxruntime>=1.17",
    # "onnx>=1.15",
    # "ml-dtypes>=0.3.1",
    # "opencv-python-headless",
    "python-dotenv",
    "pillow",
    # "pwdlib[argon2]",
    # "pyjwt",
    "uuid",
    "pydantic",
    "pypdf",
    "jsonb",
    "watchdog",
    "inotify",
]
